name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          version: '2.x'
      - name: "Run PHPUnit"
        run: |
          sudo chmod -R 777 vendor/orchestra/testbench-core/laravel
          vendor/bin/phpunit --coverage-clover=coverage.xml
        env:
          XDEBUG_MODE: coverage
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml